### ISSUE TITLE
 Why isn't Builder a standalone package for UI?

### ISSUE THREAD

**Issue by WeDontNeedTo** [hmlongco/Builder#3]
Very nice library, thx you some much! But why Builder is just folder with source code inside this demo project?

**Comment by hmlongco** [comment]
Builder started out as an exploration of a concept, and it's still very much a work in progress. 

As I discovered with Resolver, the second I turn it into an actual library is the instant that it solidifies into something that's harder to change and that also then requires support.

But glad you like it!

**Comment by hmlongco** [comment]
Builder is now a package. Enjoy.
