### ISSUE TITLE
What about Builder without RxSwift?

### ISSUE THREAD

**Issue by cedricbahirwe** [hmlongco/Builder#6]
This is a general question!

First of all, I'd to thank the author for this awesome package, It was fun for me to explore and learn.
After going through the source code, I thought it could be possible to have `Builder` without `RxSwift`  as a dependency.

Am I maybe too ambitious, or a little bit ignorant? 
If not possible, I'd like to learn why It can not be done?!
Thanks,

**Comment by hmlongco** [comment]
One could do so. Then again, if your minimum supported version is iOS 13/14/15 you might as well use SwiftUI since you need to be there anyway in order to use Combine. (13/14)
